### ISSUE TITLE
nvim-treesitter integration

### ISSUE THREAD

**Issue by mattpolzin** [mleonidas/tree-sitter-authzed#2]
Would you mind if I submitted the following to the nvim-treesitter project? I don't want to step on any toes, but I'd love to have access to this parser with even slightly less setup living in my personal config!

https://github.com/nvim-treesitter/nvim-treesitter/compare/master...mattpolzin:nvim-treesitter:add-authzed-parser

**Comment by mleonidas** [comment]
that would be awesome! I've been meaning to get around to it myself, I just haven't had the time.

**Comment by mattpolzin** [comment]
I'm also upstreaming filetype support (starting with vim, then nvim). I know you've got a few different file extensions in your config, but I am submitting for `*.zed` initially since that's the one I know is mentioned in the current Authzed documentation.

https://github.com/vim/vim/pull/13129

**Comment by mleonidas** [comment]
sounds good to me!

**Comment by mattpolzin** [comment]
Closing now that *.zed file support has merged into vim and neovim and authzed integration with nvim-treesitter has merged as well.
